Repository nhnacademy-be6-yes-25-5/yes-25-5-front-server, pull requests merged in 2024-06, with the labels that each got.

#6 [주문] 주문서 작성 페이지 구현
  .github/pull_request_template.md
  pom.xml
  src/main/java/com/nhnacademy/frontserver1/FrontServer1Application.java
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PaymentServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/SomthingServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/domain/TakeoutType.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/SomethingAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreatePaymentRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/request/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreateOrderResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreatePaymentResponse.java
  src/main/resources/static/mail/mail.php
  src/main/resources/templates/404.html
  src/main/resources/templates/about-us.html
  src/main/resources/templates/blog-grid-sidebar.html
  src/main/resources/templates/blog-single-sidebar.html
  src/main/resources/templates/blog-single.html
  src/main/resources/templates/cart.html
  src/main/resources/templates/checkout.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/faq.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mail-success.html
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/fail.html
  src/main/resources/templates/order/success.html
  src/main/resources/templates/order/toss.html
  src/main/resources/templates/product-details.html
  src/main/resources/templates/product-grids.html
  src/main/resources/templates/product-list.html
  src/main/resources/templates/register.html
Labels: 🖥️ 개발중

#14 [주문] - 주문 시 배송비, 할인액, 포장비, 포인트를 넘겨주는 기능 추가함
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/CreatePreOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PolicyAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadTakeoutResponse.java
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#13 [주문] 주문 서버에서 포장지 리스트를 받아와 주문서에 반영하는 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PolicyAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadTakeoutResponse.java
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#16 [주문] - 토스 결제 위젯이 아닌 sdk로 변경
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/CreatePreOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/payment/CreatePaymentRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreateOrderResponse.java
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
  src/main/resources/templates/order/toss.html
Labels: 🖥️ 개발중

#15 [주문] - 결제 시, 가주문과 결제 요청 정보가 일치하는지 확인하는 기능 구현
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/payment/CreatePaymentRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreateOrderResponse.java
  src/main/resources/templates/order/toss.html
Labels: ⚡️ Simple

#17 [결제] - 결제 시, 책 아이디와 수량을 같이 넘겨줌
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/CreatePaymentsRequest.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PaymentServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/SomethingConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/ApplicationException.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/FeignClientException.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/payload/ErrorStatus.java
  src/main/java/com/nhnacademy/frontserver1/common/utils/SessionUtil.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreateOrderResponse.java
  src/main/resources/templates/order/checkout.html
Labels: 🖥️ 개발중

#24 test : cd 테스트
  src/main/resources/templates/admin-layout.html
  src/main/resources/templates/layout.html
Labels: 🖥️ 개발중

#21 feat: JWT 관련 레디스 환경설정 및 저장 기능 구현
  pom.xml
  src/main/java/com/nhnacademy/frontserver1/application/service/AuthService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AuthServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/TokenService.java
  src/main/java/com/nhnacademy/frontserver1/common/config/RedisConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/util/TokenParser.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/ViewController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/LoginUserRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/LoginUserResponse.java
  src/main/resources/application.yml
  src/main/resources/static/js/main.js
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/fragments/admin-layout.html
  src/main/resources/templates/login.html
Labels: 👀 리뷰가 필요해요

#30 관리자 페이지 (도서) crud 기능 구현
  pom.xml
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/CategoryService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/TagService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceimpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CategoryServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/TagServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CategoryAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/LikesAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/TagAdapter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CategoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/TagController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateCategoryRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateLikesRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateTagRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateBookQuantityRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateCategoryRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateLikesRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateTagRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookAPIResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/CategoryResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/LikesResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/TagResponse.java
  src/main/resources/application.yml
  src/main/resources/templates/admin/category/admin-category.html
  src/main/resources/templates/admin/product/admin-book-search.html
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/admin/tag/admin-tag.html
  src/main/resources/templates/fragments/admin-layout.html
Labels: 👀 리뷰가 필요해요

#31 chore : feignClient 배포 주소 추가함
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PolicyAdaptor.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/frontserver1/FrontServer1ApplicationTests.java
  src/test/resources/application.yml
Labels: ⚡️ Simple

#32 cd 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#33 cd 테스트
  .github/workflows/cd.yml
  Dockerfile
Labels: ⚡️ Simple

#34 test : cd 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#35 test : cd 테스트
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#38 [주문] - 결제 성공 시, 결제 성공 페이지 구현
  Dockerfile
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/handler/GlobalExceptionHandler.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadPaymentOrderResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/SuccessPaymentResponse.java
  src/main/resources/templates/error/order-fail.html
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/done.html
  src/main/resources/templates/order/fail.html
  src/main/resources/templates/order/success.html
Labels: 🖥️ 개발중

#37 [주문] - 주문 실패 시, 주문 실패 페이지를 보여주도록 구현
  Dockerfile
  src/main/java/com/nhnacademy/frontserver1/common/handler/GlobalExceptionHandler.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/resources/templates/error/order-fail.html
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#39 [ci] - 도커 이미지를 캐싱하지 않도록 변경함
  .github/workflows/ci.yml
  src/main/java/com/nhnacademy/frontserver1/infrastructure/filter/AuthenticationFilter.java
Labels: ⚡️ Simple

#41 chore : ci / cd 도커 이미지 이름 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ⚡️ Simple

#42 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#43 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#44 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ⚡️ Simple

#45 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#46 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#47 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#48 chore : 캐싱된 이미지가 아닌 새 이미지를 배포하도록 수정함
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#51 무중단 배포 테스트
  .github/workflows/cd.yml
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/ReadCartBookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadMaximumDiscountCouponResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
Labels: ⚡️ Simple

#49 [주문] - 유저 정보를 api 서버에서 받아오도록 수정함
  .github/workflows/cd.yml
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/ReadCartBookResponse.java
Labels: 🖥️ 개발중, ⚡️ Simple

#52 액세스 토큰 응답, 저장, 파싱 변경 및 구현
  pom.xml
  src/main/java/com/nhnacademy/frontserver1/FrontServer1Application.java
  src/main/java/com/nhnacademy/frontserver1/application/service/AuthService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AuthServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/TokenService.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfiguration.java
  src/main/java/com/nhnacademy/frontserver1/common/config/RedisConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/provider/JwtTokenProvider.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/ViewController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/LoginUserResponse.java
  src/main/resources/application-prod.yml
  src/main/resources/templates/login.html
  src/main/resources/templates/tokenTest.html
Labels: ⚡️ Simple

#53 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#55 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#56 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#57 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#58 test : 무중단 배포 테스트
  .github/workflows/cd.yml
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#59 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#60 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#61 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#62 Feature/blue green
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#63 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#65 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#67 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#68 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#69 Feature/blue green
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#70 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#71 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#72 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#73 test : 무중단 배포 테스트
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#74 test : 무중단 배포 테스트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  DockerFile-8041
  Dockerfile-8040
  build_and_run.sh
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#75 test : 무중단 배포 테스트
  .github/workflows/cd.yml
  Dockerfile-8041
Labels: ⚡️ Simple

#78 Feature/coupon couponAdapter url 환경변수로 변경
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/resources/templates/admin/policy/admin-policy-coupon.html
Labels: ⚡️ Simple

#80 refactor : 게이트웨이 DNS 해석 문제에 대한 테스트
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/test/java/com/nhnacademy/frontserver1/FrontServer1ApplicationTests.java
Labels: ⚡️ Simple

#81 refactor : 게이트웨이 DNS 해석 문제에 대한 테스트
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
Labels: ⚡️ Simple

#82 [주문] - 사용자 정보에 따른 주문 페이지 수정
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/CreatePreOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadMaximumDiscountCouponResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
Labels: 🖥️ 개발중, ⚡️ Simple

#84 refactor : 쿠폰 정책 목록 페이징 처리 에러 수정
  src/main/resources/templates/admin/policy/admin-policy-coupon.html
Labels: ⚡️ Simple

#89 fix : "adapter 주소 수정"
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceimpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CategoryAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/LikesAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/TagAdapter.java
Labels: ⚡️ Simple

#86 fix : 기존 할인값과 할인율 동시에 입력해야하는 문제 중 둘 중 하나만 들어가도록 버그 수정
  src/main/resources/templates/admin/policy/admin-policy-coupon.html
Labels: 👀 리뷰가 필요해요

#87 [주문] - 주문 성공 시, 주문 완료까지 페이지를 잠시 폴링하도록 변경함
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/ReadMaximumDiscountCouponRequest.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/OrderWaitingException.java
  src/main/java/com/nhnacademy/frontserver1/common/handler/GlobalExceptionHandler.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AddressAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
  src/main/resources/templates/order/address-popup.html
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요

#88 Token Cookie 추출 및 header에 담는 인터셉터 및 유틸 구현, 관련 예외 처리
  src/main/java/com/nhnacademy/frontserver1/application/service/AuthService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AuthServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/FeignClientException.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/TokenCookieMissingException.java
  src/main/java/com/nhnacademy/frontserver1/common/handler/GlobalExceptionHandler.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/provider/CookieTokenProvider.java
  src/main/java/com/nhnacademy/frontserver1/common/provider/JwtTokenProvider.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/resources/templates/tokenTest.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요

#91 feat : "naver 개발자 인증 변경"
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceimpl.java
Labels: ⚡️ Simple

#90 [JWT] - jwt 필터 수정 및 인터셉터 수정
  src/main/java/com/nhnacademy/frontserver1/application/service/AdminOrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AdminOrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/config/AppConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AdminOrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/ReadAllUserOrderStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/enumtype/OrderStatusType.java
  src/main/resources/application.yml
  src/main/resources/templates/admin/order/admin-cancel-status.html
  src/main/resources/templates/admin/order/admin-order-status.html
  src/main/resources/templates/admin/order/admin-refund-status.html
  src/main/resources/templates/admin/orderStatus/admin-order-status.html
  src/main/resources/templates/fragments/admin-layout.html
  src/main/resources/templates/order/checkout.html
Labels: 🖥️ 개발중

#96 feat : 카테고리Id, 카테고리명 입력받아 카테고리 쿠폰 정책 생성 및 조회 구현 완료
  src/main/java/com/nhnacademy/frontserver1/application/service/CouponService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CouponServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyCategoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/coupon/CouponPolicyBookRequestDTO.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/coupon/CouponPolicyCategoryRequestDTO.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/CouponPolicyCategoryResponseDTO.java
  src/main/resources/templates/admin/policy/admin-policy-coupon-category.html
  src/main/resources/templates/fragments/admin-layout.html
Labels: ⚡️ Simple, 👀 리뷰가 필요해요

#97 fix : 프론트 서버 배포환경 확인 테스트
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/resources/application-dev.yml
Labels: ⚡️ Simple

#93 파일 업로드 기능 구현 (NHN Cloud API 사용)
  .github/workflows/cd.yml
  build_and_run.sh
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/UploadImageService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UploadImageServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/UploadImageResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/templates/admin/product/admin-book-search.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: 👀 리뷰가 필요해요

#98 feat : "환경변수 설정"
  build_and_run.sh
Labels: ⚡️ Simple

#99 feat : "개발자 설정 제거"
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
Labels: ⚡️ Simple

#100 feat : "환경변수 설정"
  build_and_run.sh
Labels: ⚡️ Simple

#95 [주문] - 관리자 페이지 주문 정보 수정 기능 구현 및 다국어 처리
  src/main/java/com/nhnacademy/frontserver1/application/service/AdminOrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AdminOrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AdminOrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/ReadAllUserOrderStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/UpdateOrderStatusRequest.java
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/static/css/admin.css
  src/main/resources/templates/admin/order/admin-order-status.html
Labels: 🖥️ 개발중

#92 한 사용자에 등록된 주소들
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UsersAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/address/UserAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UserResponse.java
  src/main/resources/templates/mypage/mypage-address.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요
