Repository nhnacademy-be6-yes-25-5/yes-25-5-front-server, pull requests merged in 2024-07, with the labels that each got.

#106 Book entity 객체 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/LikesAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UsersAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LikesController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/UpdateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookResponse.java
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#105 feat : 도서쿠폰 정책 등록할때 도서명으로 검색하면 부모창에 도서id, 도서명 자동입력 기능 구현
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyCategoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookResponseDTO.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/BookCouponResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/CouponResponseDTO.java
  src/main/resources/templates/admin/policy/admin-policy-coupon-book-search.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-book.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-category-search.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-category.html
  src/main/resources/templates/product/product-details.html
Labels: 👀 리뷰가 필요해요

#107 [주문, 배송] - 마이 페이지 내, 배송 내역 조회 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PaymentServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UsersAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderHistoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/UpdateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/enumtype/OrderStatusType.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadMyOrderHistoryResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDeliveryInfoResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadPurePriceResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/UpdateOrderResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/ReadUserInfoResponse.java
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/templates/admin/order/admin-order-status.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/user-sidebar.html
  src/main/resources/templates/mypage/mypage-delivery-detail.html
  src/main/resources/templates/mypage/mypage-orderHistory.html
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/mypage/mypage-orders-history.html
Labels: 👀 리뷰가 필요해요

#111 fix : 배포환경 Thymeleaf 로드 버그에 대한 재배포 시도
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
Labels: ⚡️ Simple

#112 Feature/coupon
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#113 fix : 배포환경 Thymeleaf 로드 버그에 대한 도서 검색창 재배포
  src/main/resources/templates/admin/policy/admin-policy-coupon-book-search.html
Labels: ⚡️ Simple

#114 fix : 배포환경 Thymeleaf 로드 버그에 대한 도서 검색창 재배포
  src/main/resources/templates/admin/policy/admin-policy-coupon-book-search.html
Labels: ⚡️ Simple

#115 fix : 배포환경 Thymeleaf 로드 버그에 대한 도서 검색창 재배포
  src/main/resources/templates/admin/policy/admin-policy-coupon-book-search.html
Labels: ⚡️ Simple

#117 fix : 배포환경 Thymeleaf 로드 버그에 대한 로그 추가
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
Labels: ⚡️ Simple

#118 fix : 배포환경 Thymeleaf 로드 버그에 대한 리턴값 수정
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
Labels: ⚡️ Simple

#121 [주문] - 장바구니를 거치지 않고 바로 주문하는 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/ReadCartBookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDetailResponse.java
  src/main/resources/messages_ko.properties
  src/main/resources/templates/mypage/mypage-delivery-detail.html
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/order/success.html
Labels: 👀 리뷰가 필요해요

#122 [주문] - 비회원 주문 내역 및 배송 조회 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/OrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/ReadOrderNoneMemberRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDetailResponse.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/mypage/mypage-delivery-detail.html
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/order/orders-find.html
Labels: ⚡️ Simple

#119 feat : 도서 상세페이지에서 받을수있는 쿠폰 출력(카테고리, 도서 쿠폰)
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/CouponService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CouponServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdapter.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/BookCouponResponseDTO.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/BookDetailCouponResponseDTO.java
  src/main/resources/templates/product/product-details.html
Labels: 👀 리뷰가 필요해요

#123 Feat : 쿠폰발급 버튼 누르면 회원쿠폰 테이블에 입력되도록 구현 완료
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#120 feat : 회원 가입, 수정, 삭제, 포인트 이력, 포인트 정책 추가
  .github/workflows/cd.yml
  src/main/java/com/nhnacademy/frontserver1/application/service/PointPolicyService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PointPolicyServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/config/util/TokenParser.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PointPolicyAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PointController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PointPolicyController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/CreateUserRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/DeleteUserRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/PointPolicyRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/UpdateUserRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/ReadAllUserOrderStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/point/PointLogResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/point/PointPolicyResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UpdateUserResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UserGradeResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UserResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UsersResponse.java
  src/main/resources/application.yml
  src/main/resources/templates/admin/point/admin-point.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/user-sidebar.html
  src/main/resources/templates/mypage/mypage-address.html
  src/main/resources/templates/mypage/mypage-delete.html
  src/main/resources/templates/mypage/mypage-grade.html
  src/main/resources/templates/mypage/mypage-info.html
  src/main/resources/templates/mypage/mypage-pointLogs.html
  src/main/resources/templates/register.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요

#127 fix : 기존 쿠폰 중복되어 표시되는 버그 픽스
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#128 [배송] - 배송 조회 요청에 대해 토큰을 가지고 있으면 헤더에 담도록 변경
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
Labels: ⚡️ Simple

#129 [주문] - 반품인 주문에 대한 환불 기능 구현
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/enumtype/OrderStatusType.java
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/mypage/mypage-orders-history.html
Labels: ⚡️ Simple

#124 [마이페이지] - 포인트 및 등급 조회 api를 가져오기 위한 인터셉터 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/config/WebConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/UserInfoInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderHistoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadCartBookResponse.java
  src/main/resources/templates/mypage/mypage-orders-history.html
Labels: 👀 리뷰가 필요해요

#132 이메일찾기 구현완료
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/JwtAuthorizationRequestInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LoginController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/NewPasswordController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/RegisterController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/FindEmailRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/FindUserResponse.java
  src/main/resources/static/css/Email.css
  src/main/resources/templates/findMail/find-mail-fail.html
  src/main/resources/templates/findMail/find-mail-success.html
  src/main/resources/templates/findMail/find-mail.html
Labels: 👀 리뷰가 필요해요

#130 refresh 토큰 aop, interceptor 기능 추가
  .gitignore
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/nhnacademy/frontserver1/FrontServer1Application.java
  src/main/java/com/nhnacademy/frontserver1/application/service/AuthService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AuthServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenCookieInjectorAspect.java
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenExtractorAspect.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfiguration.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/ExpireRefreshJwtException.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/JwtException.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/RefreshTokenFailedException.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/jwt/annotation/SkipTokenInjection.java
  src/main/java/com/nhnacademy/frontserver1/common/provider/CookieTokenProvider.java
  src/main/java/com/nhnacademy/frontserver1/common/utils/TokenRefresher.java
  src/main/java/com/nhnacademy/frontserver1/common/utils/TokenStorage.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/auth/CreateAccessTokenRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/auth/CreateAccessTokenResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/AuthResponse.java
  src/main/resources/application.yml
  src/main/resources/templates/error/auth-fail.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/layout.html
Labels: 👀 리뷰가 필요해요

#131 "태그 페이징 처리 오류 수정 및 페이지 각종 버그 수정 및 관리자 카테고리 페이지 카테고리 바 추가"
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookSearchAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookSearchController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CategoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyCategoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/HomeController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/TagController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/BookSearchRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateBookRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookIndexResponse.java
  src/main/resources/static/css/admin.css
  src/main/resources/templates/admin/category/admin-category.html
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/admin/tag/admin-tag.html
  src/main/resources/templates/fragments/admin-layout.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/product-details.html
  src/main/resources/templates/product/product-list.html
Labels: 👀 리뷰가 필요해요

#136 fix: "로그인 메서드 쿠키 삽입 기능 삭제"
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenCookieInjectorAspect.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
Labels: ⚡️ Simple

#137 fix: 안 쓰는 컴포넌트 삭제
  src/main/java/com/nhnacademy/frontserver1/common/utils/TokenRefresher.java
  src/main/java/com/nhnacademy/frontserver1/common/utils/TokenStorage.java
Labels: ⚡️ Simple

#140 fix : 비회원일 경우 유저 사이드바 비회원 처리
  src/main/resources/templates/fragments/user-sidebar.html
Labels: ⚡️ Simple

#144 [주문] - 관리자 환불 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/AdminOrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/ReviewService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AdminOrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/WebConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/UserInfoInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/domain/CancelStatus.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AdminOrderAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/ReviewAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserCouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminOrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/ReviewController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CancelOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/review/CreateReviewRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/review/UpdateReviewRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/CancelOrderResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/ReadAllUserOrderCancelStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDetailResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadPurePriceResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadUserCouponResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/review/ReadReviewRatingResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/review/ReadReviewResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/ReadUserInfoResponse.java
  src/main/resources/application.yml
  src/main/resources/static/css/grade-benefit.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/orderDetail.css
  src/main/resources/static/css/review.css
  src/main/resources/static/js/review.js
  src/main/resources/templates/admin/order/admin-refund-status.html
  src/main/resources/templates/fragments/admin-layout.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/fragments/review.html
  src/main/resources/templates/fragments/user-sidebar.html
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/mypage/mypage-orders-history.html
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/product/product-details.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요

#150 [주문] - 마이 페이지 주문 내역에 회원 등급 보여주는 기능 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/AuthService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/AuthServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/DormantController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderHistoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadPurePriceResponse.java
  src/main/resources/static/css/review.css
  src/main/resources/static/js/dormant.js
  src/main/resources/templates/mypage/mypage-orders-history.html
Labels: ⚡️ Simple, 👀 리뷰가 필요해요

#151 feat : 헤더 관리자 페이지 이동 추가 및 푸터 스웨거 추가
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
Labels: ⚡️ Simple

#148 카테고리 리스트 정렬 기능 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookSearchAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookSearchController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/HomeController.java
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
Labels: 👀 리뷰가 필요해요

#154 fix : "신상품 정렬 제거"
  src/main/resources/templates/product/product-list.html
Labels: ⚡️ Simple

#155 Feature/sort
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
Labels: ⚡️ Simple

#156 도커 시간대 변경 테스트
  Dockerfile-8040
  Dockerfile-8041
Labels: ⚡️ Simple

#162 [주문] - 다양한 결제 수단 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PaymentServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/resources/static/images/payment/kakao-payment.png
  src/main/resources/static/images/payment/naver-payment.png
  src/main/resources/static/images/payment/toss-payment.png
  src/main/resources/static/js/GeneralPaymentService.js
  src/main/resources/static/js/KakaoPaymentService.js
  src/main/resources/static/js/NaverPaymentService.js
  src/main/resources/static/js/PaymentService.js
  src/main/resources/static/js/TossPaymentService.js
  src/main/resources/static/js/paymentFactory.js
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
Labels: 🖥️ 개발중, 👀 리뷰가 필요해요

#159 [주문, 결제] - 0원 결제 되도록 변경
  src/main/java/com/nhnacademy/frontserver1/application/service/PaymentService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/PaymentServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/PaymentAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
Labels: ⚡️ Simple, 👀 리뷰가 필요해요

#160 재발급된 토큰으로 쿠키 및 feignClient header에 담아주는 로직 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenCookieInjectorAspect.java
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenExtractorAspect.java
  src/main/java/com/nhnacademy/frontserver1/common/config/FeignClientConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/config/WebConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/context/TokenContext.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/ReviewAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/resources/application-dev.yml
  src/main/resources/static/images/logo/payco-logo 2.png
Labels: 👀 리뷰가 필요해요

#161 좋아요 기능 오류 수정 완료 및 기능 구현 완료
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/LikesNotLoginException.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/LikesAdapter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LikesController.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/mypage/mypage-likes.html
  src/main/resources/templates/product/product-details.html
Labels: 👀 리뷰가 필요해요

#166 Feature/coupon
  src/main/resources/templates/admin/policy/admin-policy-coupon-book.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-category.html
  src/main/resources/templates/admin/policy/admin-policy-coupon.html
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#167 Feature/sort
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/LikesAdapter.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LikesController.java
Labels: ⚡️ Simple

#169 fix : "ResponseEntity로 받아오는 것으로 수정"
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
Labels: ⚡️ Simple

#165 비회원, 회원 모두 사용 가능한 기능 고려해서 aop 수정
  src/main/java/com/nhnacademy/frontserver1/common/aop/TokenExtractorAspect.java
Labels: ⚡️ Simple

#168 [장바구니] - 상품 목록에서 바로 장바구니에 추가하는 버튼 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/ReviewService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/ReviewAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/ReviewHistoryController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/review/ReadMyReviewResponse.java
  src/main/resources/static/js/productCart.js
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage/mypage-review.html
  src/main/resources/templates/product/product-list.html
Labels: ⚡️ Simple

#172 TokenContext Null, isEmpty 체크부분 수정
  src/main/java/com/nhnacademy/frontserver1/common/context/TokenContext.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UsersAdaptor.java
Labels: ⚡️ Simple

#175 도서 관련 다국어처리
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LikesController.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/templates/admin/category/admin-category.html
  src/main/resources/templates/admin/product/admin-book-search.html
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/admin/tag/admin-tag.html
  src/main/resources/templates/index.html
  src/main/resources/templates/message.html
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
Labels: ⚡️ Simple

#176 FeignJwtTokenInterceptor 토큰 유효 검사 조건 수정
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
Labels: ⚡️ Simple

#178 예외 처리
  src/main/java/com/nhnacademy/frontserver1/application/service/BookService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/BookServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/BookAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/LikesController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookResponse.java
  src/main/resources/templates/admin/product/admin-product.html
Labels: ⚡️ Simple

#179 fix : "다국어 처리 중 오류 수정"
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookSearchController.java
  src/main/resources/templates/product/product-list.html
Labels: ⚡️ Simple

#180 로그인 상태에 따른 예외처리
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/AccessDeniedException.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/utils/CookieUtils.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AuthContorller.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/resources/templates/error/auth-fail.html
  src/main/resources/templates/fragments/header.html
Labels: ⚡️ Simple

#183 도서 추가 시 설명 자동으로 안 들어가는 버그 수정
  src/main/resources/templates/admin/category/admin-category.html
  src/main/resources/templates/admin/product/admin-book-search.html
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/admin/tag/admin-tag.html
Labels: ⚡️ Simple

#182 fix: "로그인 후 메인페이지 이동시 파라미터로 토큰 노출되는 거 수정"
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CartController.java
  src/main/resources/static/js/productCart.js
Labels: ⚡️ Simple

#157 feat : 회원 주소 추가 기능 구현, 기본 배송지 설정 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/CreateUserAddressRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/user/UpdateAddressBasedRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/address/UsersAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/CreateUserAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UserAddressResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/user/UsersResponse.java
  src/main/resources/templates/fragments/user-sidebar.html
  src/main/resources/templates/mypage/mypage-address.html
Labels: 👀 리뷰가 필요해요

#186 위즈윅 에디터 버그 수정
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/book/CreateBookRequest.java
  src/main/resources/templates/admin/product/admin-book-search.html
Labels: ⚡️ Simple

#177 feat : 쿠폰정책 다국어(English, Korean) 지원 기능 구현
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CouponServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyCategoryController.java
  src/main/resources/templates/admin/policy/admin-policy-coupon-book-search.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-book.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-category-search.html
  src/main/resources/templates/admin/policy/admin-policy-coupon-category.html
  src/main/resources/templates/admin/policy/admin-policy-coupon.html
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple, 👀 리뷰가 필요해요

#197 fix : 도커파일 RUN 명령어 종료 하도록 버그 픽스
  Dockerfile-8041
Labels: ⚡️ Simple

#185 [장바구니] - 헤더 장바구니 미리보기 추가
  .github/workflows/cd.yml
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/config/WebConfig.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/CartInfoInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserCouponAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadMaximumDiscountCouponResponse.java
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/main.css
  src/main/resources/static/js/productCart.js
  src/main/resources/templates/coupon/popup.html
  src/main/resources/templates/error/server-fail.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/order/address-popup.html
  src/main/resources/templates/order/checkout.html
Labels: 👀 리뷰가 필요해요

#201 fix : yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#203 fix : 도커파일 수정
  Dockerfile-8040
  Dockerfile-8041
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
Labels: ⚡️ Simple

#204 fix : 도커파일 수정
  .github/workflows/cd.yml
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
Labels: ⚡️ Simple

#205 fix : cd 파일 수정
  .github/workflows/cd.yml
Labels: ⚡️ Simple

#206 Feature/header cart
  .github/workflows/cd.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ⚡️ Simple

#209 cart-book ResponseEntity로 수정
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CartServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/TokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
Labels: ⚡️ Simple

#194 오류 처리
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/common/exception/BookException.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
Labels: ⚡️ Simple

#211 도서관련 프론트 수정
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/HomeController.java
  src/main/resources/templates/admin/product/admin-product.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#210 Feature/coupon 쿠폰 발급 예외처리 상세화 및 페이징 기본값 수정
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CouponPolicyCategoryController.java
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#212 도서 생성 시 예외 처리
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/AdminBookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/book/BookIndexResponse.java
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
Labels: ⚡️ Simple

#213 fix : "wysiwyg 에디터 기본 markdown으로 변경"
  src/main/resources/templates/admin/product/admin-product.html
Labels: ⚡️ Simple

#215 홈 화면 인기도서로 안뜨는 오류 수정
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/HomeController.java
Labels: ⚡️ Simple

#218 main, detail, signup css 수정
  src/main/resources/messages_ko.properties
  src/main/resources/static/css/main.css
  src/main/resources/templates/contact.html
  src/main/resources/templates/findMail/find-mail.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage/mypage-address.html
  src/main/resources/templates/mypage/mypage-coupon.html
  src/main/resources/templates/mypage/mypage-delete.html
  src/main/resources/templates/mypage/mypage-delivery-detail.html
  src/main/resources/templates/mypage/mypage-info.html
  src/main/resources/templates/mypage/mypage-likes.html
  src/main/resources/templates/mypage/mypage-orders-history.html
  src/main/resources/templates/mypage/mypage-pointLogs.html
  src/main/resources/templates/mypage/mypage-review.html
  src/main/resources/templates/order/orders-find.html
  src/main/resources/templates/product/product-details.html
  src/main/resources/templates/product/product-grids.html
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
  src/main/resources/templates/register-payco.html
  src/main/resources/templates/register.html
  src/main/resources/templates/setNewPassword/set-new-password-fail.html
  src/main/resources/templates/setNewPassword/set-new-password-success.html
  src/main/resources/templates/setNewPassword/set-new-password.html
Labels: ⚡️ Simple

#219 [주문] - 주문서 배송예정일 및 포인트 제한 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/CartService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CartServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/CartInfoInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/CartAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/CartController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/cart/CreateCartResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/cart/UpdateCartBookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadCartBookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderUserInfoResponse.java
  src/main/resources/static/js/GeneralPaymentService.js
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#221 [주문, 쿠폰] -최소 주문 금액을 만족하지 않으면 쿠폰을 선택할 수 없도록 변경
  src/main/resources/static/css/checkout.css
  src/main/resources/static/css/main.css
  src/main/resources/templates/coupon/popup.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#222 [주문] - 라디오 타입 변경으로 인한 포장, 결제 타입 인식 오류 해결
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#223 프론트 (좋아요 페이지 사진 크기 수정)
  src/main/resources/templates/mypage/mypage-likes.html
Labels: ⚡️ Simple

#224 [주문] - 결제 정보 라디오 버튼 -> 스위치로 변경
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#225 fix: "장바구니, 계산서 view css 수정"
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/AuthAdaptor.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/main.css
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#226 [주문] - 주문서 페이지 포인트탭 수정
  src/main/resources/templates/order/checkout.html
Labels: ⚡️ Simple

#228 [장바구니] - 장바구니 여백으로 인한 스타일 변경
  src/main/resources/static/css/cart.css
Labels: ⚡️ Simple

#229 [주문] - 주문 시, 도서별 쿠폰 개별 적용되도록 변경
  src/main/java/com/nhnacademy/frontserver1/application/service/OrderService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/coupon/ReadAvailableUserCouponResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadCartBookResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadUserCouponResponse.java
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/coupon/popup.html
  src/main/resources/templates/order/checkout.html
Labels: 👀 리뷰가 필요해요

#230 [주문, 결제] - 결제, 주문 내역, 변경 기능에 결제 제공자 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/dto/request/CreatePaymentsRequest.java
  src/main/java/com/nhnacademy/frontserver1/domain/PaymentProvider.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CancelOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/CreateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/order/UpdateOrderRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/request/payment/CreatePaymentRequest.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/admin/ReadAllUserOrderCancelStatusResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/CreateOrderResponse.java
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDetailResponse.java
  src/main/resources/static/js/TossPaymentService.js
  src/main/resources/templates/admin/order/admin-refund-status.html
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/order/checkout.html
  src/main/resources/templates/order/success.html
Labels: 👀 리뷰가 필요해요

#234 fix: "refresh Token 만료시 예외처리 수정"
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/resources/templates/error/auth-fail.html
Labels: ⚡️ Simple

#235 fix: "refresh Token 만료시 예외처리 수정"
  src/main/java/com/nhnacademy/frontserver1/common/advice/GlobalControllerAdvice.java
Labels: ⚡️ Simple

#236 [주문, 회원] 엑세스 토큰 재발급을 위한 ResponseEntity 추가
  src/main/java/com/nhnacademy/frontserver1/application/service/UserService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/UserServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserAdaptor.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/UserController.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/messages_ko.properties
  src/main/resources/templates/mypage/mypage-info.html
  src/main/resources/templates/register.html
Labels: ⚡️ Simple

#237 [회원 쿠폰] - ResponseEntity를 사용하지 않아 엑세스 토큰을 재발급받지 못하는 이슈 수정
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/infrastructure/adaptor/UserCouponAdaptor.java
Labels: ⚡️ Simple

#240 정렬 기준 추가
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/BookSearchController.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
Labels: ⚡️ Simple

#239 [결제] - 결제창을 닫아도 다시 결제를 이어서 할 수 있도록 수정
  src/main/java/com/nhnacademy/frontserver1/application/service/CartService.java
  src/main/java/com/nhnacademy/frontserver1/application/service/impl/CartServiceImpl.java
  src/main/java/com/nhnacademy/frontserver1/common/converter/StringToPaymentProviderConverter.java
  src/main/java/com/nhnacademy/frontserver1/common/decoder/CustomErrorDecoder.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/OrderController.java
  src/main/java/com/nhnacademy/frontserver1/presentation/controller/PaymentController.java
  src/main/resources/static/js/TossPaymentService.js
  src/main/resources/templates/order/checkout.html
Labels: 👀 리뷰가 필요해요

#241 [장바구니, 배송] - 도서 상세 페이지 내 배송 조회 url 수정 및 장바구니 담기 시 페이지 새로고침 하도록 변경
  src/main/java/com/nhnacademy/frontserver1/presentation/dto/response/order/ReadOrderDetailResponse.java
  src/main/resources/static/js/productCart.js
  src/main/resources/templates/mypage/mypage-orders-detail.html
  src/main/resources/templates/product/product-details.html
Labels: ⚡️ Simple

#242 상세 페이지에 좋아요 표시 안되는 버그 수정
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
Labels: ⚡️ Simple

#243 fix : "이미지를 눌러도 상세 페이지로 이동 가능하게 수정"
  src/main/resources/templates/index.html
  src/main/resources/templates/product/product-list.html
  src/main/resources/templates/product/product-search-list.html
Labels: ⚡️ Simple

#247 [주문] - 비회원 결제 확정 시, 토큰 확인하지 않도록 변경
  src/main/java/com/nhnacademy/frontserver1/common/interceptor/FeignJwtTokenInterceptor.java
Labels: ⚡️ Simple
